[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://seu-backend-url.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://seu-backend-staging.com"

